### ISSUE TITLE
Rate limiting is applied to sendCertificate

### ISSUE THREAD

**Issue by Freyskeyd** [agglayer/agglayer#271]
As an **AggLayer node**, I want to be able to rate limit the submission of certificates on my JSON-RPC API, so that CDKs can't abuse the settlement.

### Linked tickets

- [x] Update the configuration to handle rate limiting configuration
- [x] Define and implement the different response returned by the AggLayer in case of reaching a limit
  - #222 
- [ ] Implement the rate limiting logic on both `sendTx` and `sendCertificate` RPC
    - #291
    - #271
- [ ] Add documentation related to the error codes returned by the JSON-RPC api

### Acceptance Criteria

- [ ] Sending a `Certificate` to the API increment the counter for one network
- [ ] Sending a `Certificate` while having reach the limit returns an error

### Definition of Done

- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Necessary tests are written and pass.
- [ ] Documentation is updated, if applicable.
- [ ] Feature is part of a release (created or planned).

### Related issues
- #213 
- #219

**Comment by Freyskeyd** [comment]
Based on the meeting of today:

## Outcome

We discuss that to be future-proof on how we want to manage the certificates as inputs, we'll have to cover those cases:

- Prevent overwriting a certificate that as already started its proving process
- Allow replacement of a certificate that is still in `pending` or `InError`
- Keep processing only one cert at a time
- Define a pre-check list that `transient` certificates should meet to be placed in `pending`

### Prevent overwriting a certificate that as already started its proving process

The problem can appear if a chain resubmit a different certificate at the same height, while the previous one is already in the proving process:

<div align="center">

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/e4393475-427d-456a-b082-b523c0e91975">
  <img alt="" width=700 src="https://github.com/user-attachments/assets/c1be8e26-6ef3-43bd-9fbd-d768b10ec9f1">
</picture>

</div>

What we explored was defining a new `status` for the certificate (we currently don't have a name for this status), this status would mean that the certificate as been fetched from the pending pool by the network task, and is in the proving process, thus it can be replaced.

<div align="center">

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/294f0225-dc22-4da5-a8c7-f2e59460e889">
  <img alt="" width=700 src="https://github.com/user-attachments/assets/d27e6dad-443c-45ed-a7cc-1058dc46a02a">
</picture>

</div>

### Allow replacement of a certificate that is still in `pending` or `InError`

When a `certificate` is in `Pending` or `InError`, it can be replaced by the chain (for any reason).
This is mandatory to avoid having stuck chains.

Basically, if we take the status definition above, we can define this like that:

<div align="center">

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/09fd322e-05db-49bd-9956-7fa79405db67">
  <img alt="" width=700 src="https://github.com/user-attachments/assets/d8d0107b-d9ad-48c6-996a-023ab62fb191">
</picture>

</div>

### Define a pre-check list that `transient` certificates should meet to be placed in `pending`

In order to `pre-check` the `transient` certificates, we need to define what kind of things we need to verify. If the certificate passes the checks, it is place in `pending`. Any new certificate push as a replacement should be tested again as a new one.

The different checks could be:

- Status of pre-existing certificate at same height
- Signature checking or consensus hash checking
- Shape and correctness of the certificates
- Height expectation, it should be gapless and match the rate limiting
- LER checking

## TODO

- [ ] Find a suitable name for the new status
- [ ] Define if we need to re-check following certificates in case of one being replaced.
- [ ] Explore if we need or should do more checks

**Comment by iljakuklic** [comment]
Thanks for the writeup @Freyskeyd.

A couple of notes:

* As for the name of the new status, these came to my mind: `Scheduled`, `Ready`, `Started`. None of them particularly descriptive so it would require further explanation.
* The status diagram suggests a pre-check fail puts the certificate in the `InError` status. However, I don't think the certificate should be stored in this case. The pre-check also servers as a spam/DoS barrier.

For the record, here's my current idea of how the whole certificate processing pipeline looks like from the point of view of a single certificate, showing which components are responsible for various stages in certificate processing:

![CertificateProcessing](https://github.com/user-attachments/assets/f06698e8-f969-454b-8d30-418cf04db7d6)

* Only the happy path is shown above.
* Crucially, the network task is able to process other events in spaces where it's shown as idle in the diagram. These include:
  * Receiving another certificate and performing prechecks on it.
  * Advancing the current epoch by listening to `EpochEnded` events.
* Currently, the settlement task (notifier) updates the certificate status to `Settled` while all the other status changes are written by the network task. It would probably be cleaner for the network task to be responsible for all the status updates as hinted in the diagram. Any issues with this you can think of let me know.
