### ISSUE TITLE
Smart contract can handle AggLayer's pessimistic proof settlement request

### ISSUE THREAD

**Issue by krlosMata** [agglayer/agglayer#283]
As a SC, I want to have everything setup for the pessimistic proof, so that AggLayer node can settle generated PP.

## Todo
- SC needs to handle the final proof built by the AggLayer
  - `zk-chains` to not update its `LER` but create a commitment to force `aggLayer` to include `LER` into `RER`
  - migrate all consensus of Sovereign chains to the `aggLayer` state root
  - adapt `verifyPP` public inputs functionality to work with the final proof aggregated
  - force changes on `consensusHashes` (maybe it will done directly in the `AggLayer`)

### Pending questions and comments

- [ ] Most of the work depends on the final approach on the `AggLayer` next version
- [ ] Do we need to be careful about breaking changes somewhere ?
- [ ] As defined in [this](https://github.com/agglayer/agglayer/issues/281) ticket, what are our possibilities in regard of retries and conflicts ?

### Definition of Done
- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Necessary tests are written and pass.
- [ ] Documentation is updated, if applicable.
- [ ] Feature is part of a release (created or planned).

**Comment by Freyskeyd** [comment]
@krlosMata I think that part of this ticket is done, should we split this one into multiple ones?

**Comment by krlosMata** [comment]
This issue is quite outdated and related now to AL v0.4.0.
We can close it for now until we have clear path on the Sc development in v0.4.0
